modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory
license="BSD (3 Clause)"

[[mods]] #mandatory
modId="naturaltrees" #mandatory
version="${version}" #mandatory
displayName="Natural Teees" #mandatory
description='''
Adds a simple means to carry thigns with you
'''
issueTrackerURL="https://github.com/gigaherz/NaturalTrees/issues" #optional
displayURL="https://github.com/gigaherz/NaturalTrees" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional

[[dependencies.naturaltrees]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.naturaltrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"