@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.nattrees.branch;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;